# netlify.toml
base = "app"
[build]
command = "npm run build"
publish = ".output/public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[dev]
command = "nuxi dev"
targetPort = 3000
port = 8888
framework = "#custom"



