[build]
  command = "echo no build"
  publish = "."

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"


[functions."consolida-batch"]
  schedule = "*/15 * * * *"  # Executa a cada 15 minutos
